# Generated by Django 3.2.4 on 2021-07-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210729_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_hidden',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_starred',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.folder'),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
